{ pkgs }:
let
  depsJson = builtins.fromJSON (builtins.readFile ../deps.json);

  v8-source = pkgs.fetchgit {
    url = "https://chromium.googlesource.com/v8/v8.git";
    rev = depsJson.v8_revision;
    sha256 = depsJson.v8_hash;
  };

  fetchDep =
    name: dep:
    pkgs.fetchgit {
      inherit (dep) url rev sha256;
    };

  deps = builtins.mapAttrs fetchDep depsJson.dependencies;

  gn = pkgs.fetchzip {
    url = "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest";
    extension = "zip";
    sha256 = "sha256-m27LW9J6SyaS4HYt52bzi+zAT9SkgyBbSRlx0FBBKzw=";
    stripRoot = false;
  };

  v8-deps = pkgs.runCommand "v8-deps-${depsJson.v8_revision}" { } ''
    cp -r ${v8-source} src
    chmod -R u+w src

    ${builtins.concatStringsSep "\n" (
      builtins.attrValues (
        builtins.mapAttrs (name: dep: ''
          mkdir -p src/$(dirname "${name}")
          cp -r ${dep} src/${name}
          chmod -R u+w src/${name}
        '') deps
      )
    )}

    mkdir -p src/build/config
    echo "# generated by nix/package.nix" > src/build/config/gclient_args.gni

    cp -r . $out/
  '';

  v8-clang = pkgs.stdenv.mkDerivation {
    pname = "v8-clang";
    version = depsJson.v8_revision;

    src = v8-deps;
    dontConfigure = true;

    nativeBuildInputs = with pkgs; [
      python3
      curl
      wget
      cacert
    ];

    outputHash = "sha256-9fA7FhV6cxx40cmyU2K6i3rmE2WHl8893ITNjvehCzw=";
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";

    buildPhase = ''
      python3 src/tools/clang/scripts/update.py --output-dir=$out
    '';

    installPhase = '''';
  };

  v8-prebuild = pkgs.runCommand "v8-prebuild-${depsJson.v8_revision}" { } ''
    cp -r ${v8-deps} ./v8
    chmod -R u+w ./v8
    cd v8
    cp ${../src/binding.cpp} src/
    cp ${../src/inspector.h} src/
    mkdir -p src/zig
    cp ${../build-tools/BUILD.gn} src/zig/
    cp ${../build-tools/.gn} ./
    cp -r . $out/
  '';

  v8 = pkgs.stdenv.mkDerivation {
    pname = "v8";
    version = depsJson.v8_revision;
    src = ../.;

    nativeBuildInputs = with pkgs; [
      (buildFHSEnv {
        name = "v8-fhs";
        targetPkgs =
          pkgs: with pkgs; [
            ninja
            python3
            pkg-config
            expat.dev
            glib.dev
            glibc.dev
            zlib
            gcc_multi
            gcc-unwrapped
          ];
      })
    ];

    configurePhase = ''
      cp -r ${v8-deps} ./v8
      chmod -R u+w ./v8
      cd v8

      cp ../src/binding.cpp src/
      cp ../src/inspector.h src/

      mkdir -p src/zig
      cp ../build-tools/BUILD.gn src/zig/
      cp ../build-tools/.gn ./

      v8-fhs -c '${gn}/gn \
        --root=src \
        --root-target=//zig \
        --dotfile=.gn \
        gen out \
        --args="
          is_debug=false
          symbol_level=0
          is_official_build=false

          clang_base_path=\"${v8-clang}\"
          clang_use_chrome_plugins=false
          treat_warnings_as_errors=false
        "'
    '';

    buildPhase = ''
      v8-fhs -c 'ninja -C out "c_v8"'
    '';

    installPhase = ''
      cp -r out $out/
    '';

    enableParallelBuilding = true;
  };

in
{
  v8-source = v8-source;
  v8-deps = v8-deps;
  v8-clang = v8-clang;
  v8-prebuild = v8-prebuild;
  v8 = v8;
}
