const std = @import("std");

const LazyPath = std.Build.LazyPath;

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    var build_opts = b.addOptions();
    build_opts.addOption(
        bool,
        "inspector_subtype",
        b.option(bool, "inspector_subtype", "Export default valueSubtype and descriptionForValueSubtype") orelse true,
    );

    // the module we export as a library
    const v8_module = b.addModule("v8", .{
        .root_source_file = b.path("src/v8.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .link_libcpp = true,
    });
    v8_module.addIncludePath(b.path("src"));
    v8_module.addImport("default_exports", build_opts.createModule());

    const prepared_v8 = try prepareV8Sources(b);
    const update_clang = updateClangSources(b, prepared_v8);
    const tools_dir = try downloadTools(b);
    const v8_built = try buildV8(b, prepared_v8, update_clang, tools_dir, target, optimize);

    const prepare_step = b.step("prepare-v8", "Prepare V8 source code and dependencies");
    prepare_step.dependOn(&prepared_v8.step);
    prepare_step.dependOn(&update_clang.step);

    const tools_step = b.step("download-tools-v8", "Download V8 Build Tools");
    tools_step.dependOn(&tools_dir.step);

    const build_step = b.step("build-v8", "Build v8");
    build_step.dependOn(&v8_built.step);

    {
        const test_module = b.createModule(.{
            .root_source_file = b.path("src/v8.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
            .link_libcpp = true,
        });

        // test
        const tests = b.addTest(.{
            .root_module = test_module,
        });
        tests.root_module.addImport("default_exports", build_opts.createModule());

        const release_dir = if (optimize == .Debug) "debug" else "release";
        const os = switch (target.result.os.tag) {
            .linux => "linux",
            .macos => "macos",
            .ios => "ios",
            else => return error.UnsupportedPlatform,
        };

        tests.addObjectFile(b.path(b.fmt("v8/out/{s}/{s}/obj/zig/libc_v8.a", .{ os, release_dir })));
        tests.addIncludePath(b.path("src"));

        switch (target.result.os.tag) {
            .macos => {
                // v8 has a dependency, abseil-cpp, which, on Mac, uses CoreFoundation
                tests.addSystemFrameworkPath(.{ .cwd_relative = "/System/Library/Frameworks" });
                tests.linkFramework("CoreFoundation");
            },
            else => {},
        }

        const run_tests = b.addRunArtifact(tests);
        const tests_step = b.step("test", "Run unit tests");
        tests_step.dependOn(&run_tests.step);
    }
}

fn prepareV8Sources(b: *std.Build) !*std.Build.Step.WriteFile {
    const wf = b.addWriteFiles();

    const v8_dep = b.dependency("v8_src", .{});
    _ = wf.addCopyDirectory(v8_dep.path(""), ".", .{});

    // Copy all dependencies
    const deps = [_][]const u8{
        "build",
        "buildtools",
        "third_party/dragonbox/src",
        "third_party/fp16/src",
        "third_party/fast_float/src",
        "third_party/simdutf",
        "third_party/googletest/src",
        "third_party/highway/src",
        "third_party/icu",
        "third_party/jinja2",
        "third_party/libc++/src",
        "third_party/libc++abi/src",
        "third_party/llvm-libc/src",
        "third_party/markupsafe",
        "third_party/zlib",
        "tools/clang",
        "third_party/abseil-cpp",
    };

    for (deps) |dep_name| {
        const dep = b.dependency(dep_name, .{});
        _ = wf.addCopyDirectory(dep.path(""), dep_name, .{});
    }

    // Copy binding files
    _ = wf.addCopyFile(b.path("src/binding.cpp"), "binding.cpp");
    _ = wf.addCopyFile(b.path("src/inspector.h"), "inspector.h");

    // Copy build configuration
    _ = wf.addCopyFile(b.path("build-tools/BUILD.gn"), "zig/BUILD.gn");
    _ = wf.addCopyFile(v8_dep.path("BUILD.gn"), "./BUILD.gn");

    // Not sure if it's a Zig bug or intended behavior but, `addCopyFile` won't
    // overwrite the original `.gn`. This means we put it in here and just call it from there.
    _ = wf.addCopyFile(b.path("build-tools/.gn"), "zig/.gn");

    // Generate gclient_args.gni
    _ = wf.add("build/config/gclient_args.gni",
        \\# Generated by Zig build system
        \\
    );

    return wf;
}

fn updateClangSources(b: *std.Build, prepared_v8: *std.Build.Step.WriteFile) *std.Build.Step.Run {
    // Run clang update script after copying
    const clang_update = b.addSystemCommand(&.{
        "python3",
        "tools/clang/scripts/update.py",
    });
    clang_update.setCwd(prepared_v8.getDirectory());

    return clang_update;
}

fn downloadTools(b: *std.Build) !*std.Build.Step.WriteFile {
    const tools_wf = b.addWriteFiles();

    // Download GN
    const download_gn = b.addSystemCommand(&.{
        "curl",
        "-L",
        "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/latest",
        "-o",
    });

    const gn_zip = download_gn.addOutputFileArg("gn.zip");
    const unzip_gn = b.addSystemCommand(&.{ "unzip", "-o" });
    unzip_gn.addFileArg(gn_zip);
    unzip_gn.addArg("-d");
    const gn_dir = unzip_gn.addOutputDirectoryArg("gn_extracted");

    _ = tools_wf.addCopyFile(gn_dir.path(b, "gn"), "gn");

    // Download Ninja
    const download_ninja = b.addSystemCommand(&.{
        "curl",
        "-L",
        "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip",
        "-o",
    });
    const ninja_zip = download_ninja.addOutputFileArg("ninja.zip");

    const unzip_ninja = b.addSystemCommand(&.{ "unzip", "-o" });
    unzip_ninja.addFileArg(ninja_zip);
    unzip_ninja.addArg("-d");
    const ninja_dir = unzip_ninja.addOutputDirectoryArg("ninja_extracted");

    _ = tools_wf.addCopyFile(ninja_dir.path(b, "ninja"), "ninja");

    return tools_wf;
}

fn buildV8(
    b: *std.Build,
    v8_prepared: *std.Build.Step.WriteFile,
    update_clang: *std.Build.Step.Run,
    tools_dir: *std.Build.Step.WriteFile,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) !*std.Build.Step.Run {
    const v8_dir = v8_prepared.getDirectory();
    const tools = tools_dir.getDirectory();

    const allocator = b.allocator;

    const is_debug = optimize == .Debug;

    var gn_args: std.ArrayList(u8) = .empty;
    defer gn_args.deinit(allocator);

    if (is_debug) {
        try gn_args.appendSlice(allocator, "is_debug=true\n");
    } else {
        try gn_args.appendSlice(allocator, "is_debug=false\n");
    }

    try gn_args.appendSlice(allocator, "symbol_level=0\n");
    try gn_args.appendSlice(allocator, "is_official_build=false\n");
    try gn_args.appendSlice(allocator, "clang_use_chrome_plugins=false\n");
    try gn_args.appendSlice(allocator, "treat_warnings_as_errors=false\n");

    var gn_run = std.Build.Step.Run.create(b, "run gn");
    gn_run.addFileArg(tools.path(b, "gn"));
    gn_run.addArgs(&.{
        "--root=.",
        "--root-target=//zig",
        "--dotfile=zig/.gn",
        "gen",
        "out",
        b.fmt("--args={s}", .{gn_args.items}),
    });
    gn_run.setCwd(v8_dir);
    gn_run.step.dependOn(&v8_prepared.step);
    gn_run.step.dependOn(&update_clang.step);
    gn_run.step.dependOn(&tools_dir.step);

    var ninja_run = std.Build.Step.Run.create(b, "run ninja");
    ninja_run.addFileArg(tools.path(b, "ninja"));
    ninja_run.addArgs(&.{ "-C", "out", "c_v8" });
    ninja_run.setCwd(v8_dir);
    ninja_run.step.dependOn(&gn_run.step);

    _ = target;
    // const release_dir = if (is_debug) "debug" else "release";
    // const os = switch (target.result.os.tag) {
    //     .linux => "linux",
    //     .macos => "macos",
    //     else => return error.UnsupportedPlatform,
    // };

    const install_lib = b.addInstallLibFile(v8_dir.path(b, "out/obj/zig/libc_v8.a"), "libc_v8.a");
    install_lib.step.dependOn(&ninja_run.step);
    b.getInstallStep().dependOn(&install_lib.step);

    return ninja_run;
}
