name: build-release

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

env:
  ZIG_VERSION: 0.12.1

jobs:
  build-x86_64-linux:
    env:
      OS: linux
      ARCH: x86_64

    runs-on: ubuntu-latest
    steps:
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - run: zig build get-tools
      - run: zig build get-v8
      - run: zig build -Doptimize=ReleaseSafe
      - run: mv v8-build/${{ env.ARCH }}-${{ env.OS }}/release/ninja/obj/zig/libc_v8.a libc_v8_${{ env.OS }}_${{ env.ARCH }}.a

      - name: Upload the build
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: libc_v8_${{ env.OS }}_${{ env.ARCH }}.a

  build-aarch64-macos:
    env:
      OS: macos
      ARCH: aarch64

    runs-on: macos-latest
    steps:
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - run: zig build get-tools
      - run: zig build get-v8
      - run: zig build -Doptimize=ReleaseSafe
      - run: mv v8-build/${{ env.ARCH }}-${{ env.OS }}/release/ninja/obj/zig/libc_v8.a libc_v8_${{ env.OS }}_${{ env.ARCH }}.a

      - name: Upload the build
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: libc_v8_${{ env.OS }}_${{ env.ARCH }}.a
