name: build-release

on:
  push:
    tags: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-x86_64-linux:
    uses: ./.github/workflows/_prebuild-v8.yml
    with:
      runner: ubuntu-22.04
      target: x86_64-linux
      build_type: release
