name: build-release

on:
  push:
    tags: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write

jobs:
  build-x86_64-linux:
    uses: ./.github/workflows/_prebuild-v8.yml
    with:
      runner: ubuntu-22.04
      target: x86_64-linux
      build_type: release

  build-x86_64-linux-debug:
    uses: ./.github/workflows/_prebuild-v8.yml
    with:
      runner: ubuntu-22.04
      target: x86_64-linux
      build_type: debug

  build-arm64-linux:
    uses: ./.github/workflows/_prebuild-v8.yml
    with:
      runner: ubuntu-22.04-arm
      target: aarch64-linux
      build_type: release
